
#Variable-Terminal server settings file, supports UTF-8
#vate.server.connection.mode      values: P(passive, default) or A(active)
#vate.server.encryption.type      values: N(none, default), R(RC4) or A(AES)
#vate.server.proxy.type           values: N(none, default), H(HTTP) or S(SOCKS)
#vate.server.proxy.authentication values: D(disabled, default) or E(enabled)
#vate.server.authentication.users format: login1/password1;login2/password2;...
#
vate.server.connection.mode=
vate.server.connection.host=
vate.server.connection.port=
vate.server.connection.nat.port=
vate.server.encryption.type=
vate.server.encryption.password=
vate.server.proxy.type=
vate.server.proxy.host=
vate.server.proxy.port=
vate.server.proxy.authentication=
vate.server.proxy.user=
vate.server.proxy.password=
vate.server.authentication.users=
vate.server.session.limit=
